/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAuditTab: typeof import('./components/admin/AdminAuditTab.vue')['default']
    AdminChatAudit: typeof import('./components/admin/AdminChatAudit.vue')['default']
    AdminDashboard: typeof import('./components/dashboards/AdminDashboard.vue')['default']
    AdminNotificationsTab: typeof import('./components/admin/AdminNotificationsTab.vue')['default']
    AdminReportsTab: typeof import('./components/admin/AdminReportsTab.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ApprovalModal: typeof import('./components/ApprovalModal.vue')['default']
    ApprovalWarningModal: typeof import('./components/admin/ApprovalWarningModal.vue')['default']
    CalendarViewModal: typeof import('./components/CalendarViewModal.vue')['default']
    DesignerDashboard: typeof import('./components/dashboards/DesignerDashboard.vue')['default']
    FileUploadModal: typeof import('./components/FileUploadModal.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageModal: typeof import('./components/ImageModal.vue')['default']
    MediaRepository: typeof import('./components/MediaRepository.vue')['default']
    OrderDetailModal: typeof import('./components/OrderDetailModal.vue')['default']
    OrderTimeline: typeof import('./components/OrderTimeline.vue')['default']
    PendingApprovalAlertModal: typeof import('./components/admin/PendingApprovalAlertModal.vue')['default']
    ProducaoDashboard: typeof import('./components/dashboards/ProducaoDashboard.vue')['default']
    ProjectFormModal: typeof import('./components/projects/ProjectFormModal.vue')['default']
    RequestChangesModal: typeof import('./components/RequestChangesModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTraining: typeof import('./components/dashboards/SalesTraining.vue')['default']
    TaskCard: typeof import('./components/tasks/TaskCard.vue')['default']
    TaskFormModal: typeof import('./components/tasks/TaskFormModal.vue')['default']
    VendedorDashboard: typeof import('./components/dashboards/VendedorDashboard.vue')['default']
  }
}
