/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAuditTab: typeof import('./components/admin/AdminAuditTab.vue')['default']
    AdminChatAudit: typeof import('./components/admin/AdminChatAudit.vue')['default']
    AdminDashboard: typeof import('./components/dashboards/AdminDashboard.vue')['default']
    AdminNotificationsTab: typeof import('./components/admin/AdminNotificationsTab.vue')['default']
    AdminPriceListManagement: typeof import('./components/admin/AdminPriceListManagement.vue')['default']
    AdminReportsTab: typeof import('./components/admin/AdminReportsTab.vue')['default']
    AdminUserManagement: typeof import('./components/admin/AdminUserManagement.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ApprovalModal: typeof import('./components/ApprovalModal.vue')['default']
    ApprovalWarningModal: typeof import('./components/admin/ApprovalWarningModal.vue')['default']
    BillingModal: typeof import('./components/BillingModal.vue')['default']
    CalendarViewModal: typeof import('./components/CalendarViewModal.vue')['default']
    ChartCard: typeof import('./components/admin/ChartCard.vue')['default']
    ClientFormModal: typeof import('./components/ClientFormModal.vue')['default']
    DesignerDashboard: typeof import('./components/dashboards/DesignerDashboard.vue')['default']
    DminUserManagement: typeof import('./components/admin/dminUserManagement.vue')['default']
    FileUploadModal: typeof import('./components/FileUploadModal.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageModal: typeof import('./components/ImageModal.vue')['default']
    KpiCard: typeof import('./components/admin/KpiCard.vue')['default']
    LaunchDetailModal: typeof import('./components/LaunchDetailModal.vue')['default']
    LowStockAlertModal: typeof import('./components/LowStockAlertModal.vue')['default']
    MediaRepository: typeof import('./components/MediaRepository.vue')['default']
    OrderDetailModal: typeof import('./components/OrderDetailModal.vue')['default']
    OrderTimeline: typeof import('./components/OrderTimeline.vue')['default']
    PendingApprovalAlertModal: typeof import('./components/admin/PendingApprovalAlertModal.vue')['default']
    ProducaoDashboard: typeof import('./components/dashboards/ProducaoDashboard.vue')['default']
    ProjectFormModal: typeof import('./components/projects/ProjectFormModal.vue')['default']
    ReleasedForProductionModal: typeof import('./components/design/ReleasedForProductionModal.vue')['default']
    ReleaseOrderModal: typeof import('./components/production/ReleaseOrderModal.vue')['default']
    RequestChangesModal: typeof import('./components/RequestChangesModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTraining: typeof import('./components/dashboards/SalesTraining.vue')['default']
    StampCard: typeof import('./components/admin/StampCard.vue')['default']
    StampFolderCard: typeof import('./components/admin/StampFolderCard.vue')['default']
    StampFolderFormModal: typeof import('./components/admin/StampFolderFormModal.vue')['default']
    StampFormModal: typeof import('./components/admin/StampFormModal.vue')['default']
    TaskCard: typeof import('./components/tasks/TaskCard.vue')['default']
    TaskFormModal: typeof import('./components/tasks/TaskFormModal.vue')['default']
    VariationConfirmationModal: typeof import('./components/design/VariationConfirmationModal.vue')['default']
    VendedorDashboard: typeof import('./components/dashboards/VendedorDashboard.vue')['default']
  }
}
